### ISSUE TITLE
Typo on the word 'Cannavis' on vdb site https://github.com/openthc/vdb

### ISSUE THREAD

**Issue by amatic1** [openthc/vdb#1]
## Status
Typo on the word 'Cannavis' on vdb site https://github.com/openthc/vdb
![image](https://user-images.githubusercontent.com/92059125/236876341-f6f0ece8-f8db-460c-baf7-0b7a74bd5aaf.png)

## Action
Fix the word 'Cannavis' on https://github.com/openthc/vdb

**Comment by djbusby** [comment]
Fixed.
